version: '3.9'

services:
  api:
    container_name: "ConCurrency_API"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8099:8099
    env_file:
      - ".env"
    networks:
      - backend
    volumes:
      - .:/app

networks:
  backend:
    driver: bridge
